const getImagePath = '../assets/images';

export const images = {
    gabitDrySkin: require(`${getImagePath}/gabit_dry_skin.png`),
    gabitSunscreen: require(`${getImagePath}/gabit_sunscreen.png`),
    gabitSunscreenOld: require(`${getImagePath}/gabit_sunscreen_old.png`),
    avatar: require(`${getImagePath}/avatar.png`),
    gabitLogo: require(`${getImagePath}/gabit-logo.png`),
    knowMore: require(`${getImagePath}/know-more.png`),
    members: require(`${getImagePath}/members.png`),
    skinPack: require(`${getImagePath}/skin-pack.png`),
    skinType: require(`${getImagePath}/skin-type.png`),
    video: require(`${getImagePath}/video.png`),
    heart: require(`${getImagePath}/heart.png`),
    heartStrong: require(`${getImagePath}/heart-strong.png`),
    heartWhite: require(`${getImagePath}/heart-white.png`),
    search: require(`${getImagePath}/search.png`),
    star: require(`${getImagePath}/star.png`),
    offPercentage: require(`${getImagePath}/offPercentage.png`),
    pauseWhiteIcon: require(`${getImagePath}/white_pause.png`),
    fb: require(`${getImagePath}/fb.png`),
    insta: require(`${getImagePath}/insta.png`),
    twiter: require(`${getImagePath}/twiter.png`),
    upload: require(`${getImagePath}/upload.png`),
    sortIcon: require(`${getImagePath}/sort_icon.png`),
    dropdown: require(`${getImagePath}/dropdown.png`),
    bag: require(`${getImagePath}/bag.png`),
    back: require(`${getImagePath}/back.png`),
    women: require(`${getImagePath}/women.png`),
    orangeArrow: require(`${getImagePath}/orange_arrow.png`),
    mail: require(`${getImagePath}/mail.png`),
    arrowRight: require(`${getImagePath}/arrow-right.png`),
    shoppingCart: require(`${getImagePath}/shopping-cart.png`),
    rupeeSymbol: '\u20B9'
};
